apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote-app
  labels:
    name: db
spec:
  selector:
    name: db
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
