## Vote App Sample Application Kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Vote-app resources (namespace, services, deployments, etc)
resources:
  - vote-namespace.yml
  - db-deployment.yaml
  - db-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - result-deployment.yaml
  - result-service.yaml
  - worker-deployment.yaml
