apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote-app
  labels:
    name: redis
spec:
  selector:
    name: redis
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
