apiVersion: v1
kind: Service
metadata:
  namespace: vote-app
  name: result
  labels:
    name: result
spec:
  selector:
    app: result
  type: NodePort
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 32001
