apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote-app
  name: vote
  labels:
    name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote
  template:
    metadata:
      labels:
        name: vote
    spec:
      containers:
      - name: vote-app
        image: dockersamples/examplevotingapp_vote:before
        # resources:
        #   limits:
        #     memory: "80Mi"
        #     cpu: "256m"
        ports:
        - containerPort: 80
          name: vote-app
