apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote-app
  labels:
    name: vote
spec:
  selector:
    name: vote
  type: NodePort
  ports:
  - name: "vote-app-service"
    port: 5000
    targetPort: 80 #Container Port
    nodePort: 32000 #Node Port on which app will be access
