apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote-app
  labels:
    name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
        # resources:
        #   limits:
        #     memory: "90Mi"
        #     cpu: "15m"
